version: '3.1'

services:
  worklog-api:
    build:
      context: api
      args:
        - NODE_ENV=development
        - PORT=3333
    command: adonis serve --dev
    tty: true
    ports:
      - "5858:5858"
      - "9229:9229"
    volumes:
      - ./api:/opt/app:delegated
      # prevent host node_modules from accidently getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /opt/node_modules location.
      - notused_1:/opt/app/node_modules
    environment:
      - NODE_ENV=development

  worklog-frontend:
      build:
        context: frontend
        args:
          - NODE_ENV=development
          - PORT=3000
      ports:
        - "5859:5858"
        - "9230:9229"
      volumes:
        - ./frontend:/opt/app:delegated
        # prevent host node_modules from accidently getting mounted in container
        # in case you want to use node/npm both outside container for test/lint etc. and also inside container
        # this will overwrite the default node_modules dir in container so it won't conflict with our
        # /opt/node_modules location.
        - notused_2:/opt/app/node_modules
      environment:
        - NODE_ENV=development

volumes:
    notused_1:
    notused_2: