version: '3.1'

services:
  worklog-api:
    build:
      context: api
      args:
        - NODE_ENV=production
        - PORT=3333
    image: worklog-api
    command: adonis serve
    environment:
      - NODE_ENV=production
    networks:
      worklog_net:

  worklog-frontend:
    build:
      context: frontend
      args:
        - NODE_ENV=production
        - PORT=3000
    image: worklog-frontend
    environment:
      - NODE_ENV=production
    networks:
      worklog_net:

  webserver:
    build:
      context: webserver
    image: worklog-webserver
    ports:
      - "80:80"
      - "443:443"
    links:
      - worklog-frontend
      - worklog-api
    networks:
      worklog_net:
        aliases:
          - worklog-api.test
          - worklog.test

  mariadb:
    build:
      context: mariadb
    image: worklog-mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      worklog_net:

volumes:
  mariadb-data:

networks:
  worklog_net: